/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eew;

import net.proteanit.sql.DbUtils;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author dell
 */
public class AdminPage extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pstmt;
    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        super("LoginPage");
        initComponents();
        conn=connector.ConnecrDb();
        Table();
        
    }
    
    public void Table(){
        try{
            String sql = "SELECT * FROM exercise ORDER BY Ex_No ASC";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblContent.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtsearch = new javax.swing.JTextField();
        btnExSearch = new javax.swing.JButton();
        txtExname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnDelete = new javax.swing.JButton();
        btnABack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContent = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnAdminHome = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        exno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Express English Web");

        jPanel1.setLayout(null);
        jPanel1.add(txtsearch);
        txtsearch.setBounds(280, 40, 510, 30);

        btnExSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExSearch.setText("SEARCH");
        btnExSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnExSearch);
        btnExSearch.setBounds(810, 40, 110, 30);

        txtExname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtExname);
        txtExname.setBounds(240, 220, 350, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Exercise Number");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 130, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Description");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 300, 140, 22);

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 300, 350, 91);

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\EEW\\Images\\delete.png")); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setIconTextGap(15);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(730, 470, 150, 39);

        btnABack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnABack.setText("Back");
        btnABack.setIconTextGap(15);
        btnABack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnABackActionPerformed(evt);
            }
        });
        jPanel1.add(btnABack);
        btnABack.setBounds(1090, 470, 150, 40);

        tblContent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ex_No", "Ex_Name", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblContent);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(620, 110, 610, 320);

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\EEW\\Images\\update.jpg")); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setIconTextGap(15);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(560, 470, 150, 39);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\EEW\\Images\\Add.png")); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setIconTextGap(15);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(390, 470, 150, 39);

        btnAdminHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\EEW\\Images\\adminhome.png")); // NOI18N
        btnAdminHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdminHome);
        btnAdminHome.setBounds(1180, 30, 50, 50);

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\EEW\\Images\\clear.jpg")); // NOI18N
        btnClear.setText("Clear");
        btnClear.setIconTextGap(15);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(910, 470, 150, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Exercise Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 210, 170, 30);

        btnShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnShow.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\EEW\\Images\\open.png")); // NOI18N
        btnShow.setText("Show");
        btnShow.setIconTextGap(15);
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jPanel1.add(btnShow);
        btnShow.setBounds(40, 470, 150, 40);

        btnOpen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOpen.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\EEW\\Images\\open.png")); // NOI18N
        btnOpen.setText("Open");
        btnOpen.setIconTextGap(15);
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpen);
        btnOpen.setBounds(220, 470, 150, 40);

        exno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exno.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(exno);
        exno.setBounds(250, 130, 210, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\EEW\\Images\\adminpage.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1279, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnABackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnABackActionPerformed
        int discard = JOptionPane.showConfirmDialog(null,"Do you want to log out","Back",JOptionPane.YES_NO_OPTION );
        if(discard==0){
            HomePage a = new HomePage();
            a.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_btnABackActionPerformed

    private void btnAdminHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminHomeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{
            String sql="INSERT INTO exercise(ex_name,description) VALUES(?,?)";
            pstmt=conn.prepareStatement(sql);
            pstmt.setString(1,txtExname.getText());
            pstmt.setString(2, txtDescription.getText());
            pstmt.execute();
            JOptionPane.showMessageDialog(null, "New Exercise Created.");
            rs.close();
            pstmt.close();
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
        }
        Table();
        resetAllFeilds();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        resetAllFeilds();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblContentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContentMouseClicked
        int i = tblContent.getSelectedRow();
        TableModel model = tblContent.getModel();
        exno.setText(model.getValueAt(i,0).toString());
        txtExname.setText(model.getValueAt(i,1).toString());
        txtDescription.setText(model.getValueAt(i,2).toString());
      
    }//GEN-LAST:event_tblContentMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try{
            int i = tblContent.getSelectedRow();
            String value = (tblContent.getModel().getValueAt(i,0).toString());
            String sql="UPDATE exercise SET ex_name=?,description=? WHERE Ex_No="+value;
            pstmt=conn.prepareStatement(sql);
            pstmt.setString(1,txtExname.getText());
            pstmt.setString(2, txtDescription.getText());
            pstmt.execute();
            //JOptionPane.showMessageDialog(null, "Exercise is updated.");
            rs.close();
            pstmt.close();
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
        }
        try{
            int k = tblContent.getSelectedRow();
            String value = (tblContent.getModel().getValueAt(k,0).toString());
            String sql="UPDATE question SET Ex_Name=? WHERE Ex_No="+value;
            pstmt=conn.prepareStatement(sql);
            pstmt.setString(1,txtExname.getText());
            pstmt.execute();
            JOptionPane.showMessageDialog(null, "Exercise is updated.");
            rs.close();
            pstmt.close();
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
        }
        Table();
        resetAllFeilds();
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        int discard = JOptionPane.showConfirmDialog(null,"Do you want to discard this clear","Clear",JOptionPane.YES_NO_OPTION );
        if(discard==0){
            try{
            int i = tblContent.getSelectedRow();
            String value = (tblContent.getModel().getValueAt(i,0).toString());
            String sql="DELETE FROM exercise WHERE Ex_No="+value;
            pstmt=conn.prepareStatement(sql);
            pstmt.execute();
            //JOptionPane.showMessageDialog(null, "Exercise is deleted.");
            rs.close();
            pstmt.close();
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
        }
        try{
            int i = tblContent.getSelectedRow();
            String value = (tblContent.getModel().getValueAt(i,0).toString());
            String sql="DELETE FROM question WHERE Ex_No="+value;
            pstmt=conn.prepareStatement(sql);
            pstmt.execute();
            JOptionPane.showMessageDialog(null, "Exercise is deleted.");
            rs.close();
            pstmt.close();
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
        }
        }
        
        Table();
        resetAllFeilds();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExSearchActionPerformed
        Table1();
    }//GEN-LAST:event_btnExSearchActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        dispose();
        QueAddingPage k = new QueAddingPage();
        QueAddingPage.lblexername.setText(this.txtExname.getText());
        QueAddingPage.lblexno.setText(this.exno.getText());
        k.setVisible(true);
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        
    }//GEN-LAST:event_btnShowActionPerformed
    
    public void Table1(){
        try{
            
            String sql = "SELECT * FROM exercise WHERE ex_name LIKE '%"+txtsearch.getText()+ "'%";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblContent.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void resetAllFeilds() {
        this.txtExname.setText(null);
        this.txtDescription.setText(null);
        this.exno.setText(null);
    }
    
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnABack;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdminHome;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExSearch;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel exno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblContent;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtExname;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
