/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eew;
import eew.connector;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author dell
 */
public class QueAddingPage extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pstmt;
    /**
     * Creates new form QueAddingPage
     */
    public QueAddingPage() {
        super("AdminPage");
        initComponents();
        conn=connector.ConnecrDb();
        TableQues();
    }
     
       
        
    public void TableQues(){
        String fc = lblexno.getText();
        String sql = "select Que_No,Question from question where ex_no='"+fc+"' order by Que_No ASC";
        try{
            //String value = lblexername.getText().toString();
            PreparedStatement pstmt = conn.prepareStatement(sql);
            //pstmt.setString(1,lblexno.getText());
            ResultSet rs = pstmt.executeQuery();
            tblquestion.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbQueNo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taQuestion = new javax.swing.JTextArea();
        A = new javax.swing.JTextField();
        B = new javax.swing.JTextField();
        C = new javax.swing.JTextField();
        D = new javax.swing.JTextField();
        cmbCorAns = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblexername = new javax.swing.JLabel();
        lblexno = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblquestion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Express English Web");

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Answers");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 230, 170, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Question");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 130, 170, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Question No.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 80, 170, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("A");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 250, 20, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("C");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 350, 20, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("D");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 390, 20, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correct Answer");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 460, 170, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("B");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(190, 300, 20, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Exercise Name");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 20, 170, 40);

        cmbQueNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbQueNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        jPanel1.add(cmbQueNo);
        cmbQueNo.setBounds(220, 90, 100, 30);

        taQuestion.setColumns(20);
        taQuestion.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        taQuestion.setRows(5);
        jScrollPane1.setViewportView(taQuestion);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 150, 450, 70);

        A.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(A);
        A.setBounds(220, 250, 450, 30);

        B.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(B);
        B.setBounds(220, 300, 450, 30);

        C.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(C);
        C.setBounds(220, 350, 450, 30);

        D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(D);
        D.setBounds(220, 400, 450, 30);

        cmbCorAns.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbCorAns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jPanel1.add(cmbCorAns);
        cmbCorAns.setBounds(220, 470, 100, 30);

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\EEW\\Images\\clear.jpg")); // NOI18N
        btnClear.setText("Clear");
        btnClear.setIconTextGap(15);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(780, 530, 150, 40);

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\EEW\\Images\\Add.png")); // NOI18N
        btnSave.setText("Add");
        btnSave.setIconTextGap(15);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(40, 530, 150, 40);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(1030, 530, 150, 40);

        lblexername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblexername.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblexername);
        lblexername.setBounds(280, 30, 390, 30);

        lblexno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblexno.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblexno);
        lblexno.setBounds(224, 30, 50, 30);

        btndelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\EEW\\Images\\delete.png")); // NOI18N
        btndelete.setText("Delete");
        btndelete.setIconTextGap(15);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete);
        btndelete.setBounds(520, 530, 150, 40);

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\EEW\\Images\\update.jpg")); // NOI18N
        btnupdate.setText("Update");
        btnupdate.setIconTextGap(15);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate);
        btnupdate.setBounds(270, 530, 150, 40);

        tblquestion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Que_No", "Question"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblquestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblquestionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblquestion);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(700, 40, 470, 402);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\EEW\\Images\\adminpage.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1380, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
           try{
            String sql="INSERT INTO `question`(`ex_no`, `Ex_Name`, `Que_No`, `Question`, `A1`, `A2`, `A3`, `A4`, `correct_answer`) VALUES (?,?,?,?,?,?,?,?,?)";
            pstmt=conn.prepareStatement(sql);
            pstmt.setInt(1, Integer.parseInt(lblexno.getText().toString()));
            pstmt.setString(2, lblexername.getText());
            pstmt.setInt(3, Integer.parseInt(cmbQueNo.getSelectedItem().toString()));
            pstmt.setString(4, taQuestion.getText());
            pstmt.setString(5, A.getText());
            pstmt.setString(6, B.getText());
            pstmt.setString(7, C.getText());
            pstmt.setString(8, D.getText());
            pstmt.setString(9, cmbCorAns.getSelectedItem().toString());
            pstmt.execute();
            JOptionPane.showMessageDialog(null, "New question Created.");
            rs.close();
            pstmt.close();
            }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
            }
              
        TableQues();
        resetAllFeilds();
           
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        int discard = JOptionPane.showConfirmDialog(null,"Do you want to discard this clear","Clear",JOptionPane.YES_NO_OPTION );
        if(discard==0){
            taQuestion.setText("");
            A.setText("");
            C.setText("");
            B.setText("");
            D.setText("");
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
        AdminPage h = new AdminPage();
        h.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        
        int discard = JOptionPane.showConfirmDialog(null,"Do you want to delete this question","Delete",JOptionPane.YES_NO_OPTION );
        if(discard==0){
            try{
            String sql="DELETE FROM question WHERE ex_no=? AND Que_NO=?";
            pstmt=conn.prepareStatement(sql);
            pstmt.setString(1,lblexno.getText());
            pstmt.setString(2,cmbQueNo.getSelectedItem().toString());
            pstmt.execute();
            JOptionPane.showMessageDialog(null, "Exercise is deleted.");
            rs.close();
            pstmt.close();
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
        }
        }
        
        TableQues();
        resetAllFeilds();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        
        try{
            //int i = tblquestion.getSelectedRow();
            String value = cmbQueNo.getSelectedItem().toString();
            String r = lblexno.getText();
            String sql = "UPDATE question SET Question=?, A1=?, A2=?, A3=?, A4=?, correct_answer=? WHERE ex_no='"+r+"' AND Que_No='"+value+"' ";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1,taQuestion.getText());
            pstmt.setString(2, A.getText());
            pstmt.setString(3, B.getText());
            pstmt.setString(4, C.getText());
            pstmt.setString(5, D.getText());
            pstmt.setString(6, cmbCorAns.getSelectedItem().toString());
            pstmt.execute();
            JOptionPane.showMessageDialog(null, "Question is updated.");
            rs.close();
            pstmt.close();
            
            
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
        }
        TableQues();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void tblquestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblquestionMouseClicked
        int i = tblquestion.getSelectedRow();
        TableModel model = tblquestion.getModel();
        cmbQueNo.setSelectedItem(model.getValueAt(i,0).toString());
        taQuestion.setText(model.getValueAt(i,1).toString());
        try{
            String sql;
            String val = lblexno.getText();
            String r = cmbQueNo.getSelectedItem().toString();
            sql = "SELECT A1,A2,A3,A4,correct_answer FROM question WHERE ex_no='"+val+"' AND Que_No='"+r+"'";
            //pstmt.setString(1,lblexno.getText());
            //pstmt.setString(2,cmbQueNo.getSelectedItem().toString());
            pstmt = conn.prepareStatement(sql);
            rs = pstmt.executeQuery();
            while(rs.next()){
                A.setText(rs.getString("A1"));
                B.setText(rs.getString("A2"));
                C.setText(rs.getString("A3"));
                D.setText(rs.getString("A4"));                
                cmbCorAns.setSelectedItem(rs.getString("correct_answer"));
            }    
            
        } catch (Exception e) {
            //Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_tblquestionMouseClicked
    
    private void resetAllFeilds() {
        //this.cmbQueNo.setSelectedItem("<none>");
        this.taQuestion.setText(null);
        this.A.setText(null);
        this.B.setText(null);
        this.C.setText(null);
        this.D.setText(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueAddingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueAddingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueAddingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueAddingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueAddingPage().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField B;
    private javax.swing.JTextField C;
    private javax.swing.JTextField D;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cmbCorAns;
    private javax.swing.JComboBox<String> cmbQueNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lblexername;
    public static javax.swing.JLabel lblexno;
    private javax.swing.JTextArea taQuestion;
    private javax.swing.JTable tblquestion;
    // End of variables declaration//GEN-END:variables
}
